baseURL = "https://jianjustin.github.io/"
languageCode = "en-us"
title = "Jian's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"

[author]
  name = "Jian"
  homepage = "https://github.com/jianjustin"


[params]
mainSections = ["posts"]
headTitle = "Jian"
[[params.socials]]
name = "Github"
link = "https://github.com/jianjustin"